#version: '3'

elasticsearch:
  image: elasticsearch:alpine
  ports:
   - "9200:9200"
   - "9300:9300"

web:
  build: app/Docker/.
  ports:
   - "8080:8080"
  links:
   - elasticsearch:elasticsearch
  volumes:
   - ./app/api:/var/www/example.com/api


swagger:
  build: swagger-spec/.
  command: java -jar /swagger-codegen-cli.jar generate -l nodejs-server -i petstore.yaml -o generated
  volumes: ['./swagger-spec:/local']

#docker run --rm -v ${PWD}:/local swaggerapi/swagger-codegen-cli generate \
#    -i http://petstore.swagger.io/v2/swagger.json \
#        -l go \
#            -o /local/out/go

